---
- name: Déterminer le domaine de la boutique
  ansible.builtin.import_tasks: domain.yml

- name: Installer PHP
  ansible.builtin.import_tasks: php.yml

- name: Installer et configurer Apache
  ansible.builtin.import_tasks: apache.yml

- name: Télécharger et extraire PrestaShop
  ansible.builtin.import_tasks: download.yml

- name: Installer la boutique
  ansible.builtin.import_tasks: install.yml
