---
galaxy_info:
  author: Imad Sabri
  description: Installe Apache, PHP et la boutique PrestaShop reliée à une base MySQL distante
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
dependencies: []
